# lightning.pytorch==2.0.0

seed: 0
trainer:
  max_epochs: 150
  accelerator: auto
  devices: 1
  deterministic: "warn"
  fast_dev_run: false
  strategy: auto
  num_nodes: 1
  precision: 32-true
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 2
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
model:
  in_channels: 2835
  hidden_layers:
    - 200
    - 200
    - 200
  out_channels: 67
  activation:
    name: "ReLU"
    init_args: {}
  norm_layer:
    name: "none" # instance | batch | none
    init_args: {}
  dropout: 0.0
  optimizer:
    name: "AdamW"
    init_args:
      weight_decay: 0.0
  onecycle_lr_scheduler:
    max_lr: 1e-5
    cycle_momentum: false

data:
  mouse_voxel_data_path: data/mouse_human/data.ign/MouseExpressionMatrix_voxel_coronal_maskcoronal_log2_grouped_imputed_labelled_scaled.csv
  human_voxel_data_path: data/mouse_human/data.ign/HumanExpressionMatrix_samples_pipeline_abagen_labelled_scaled.csv
  mouse_region_data_path: data/mouse_human/data.ign/MouseExpressionMatrix_ROI_Region67_scaled.csv
  human_region_data_path: data/mouse_human/data.ign/HumanExpressionMatrix_ROI_Region88_scaled.csv
  mouse_labelcol: Region67
  human_labelcol: Region88
  train_bsize: 64
  valid_bsize: 64
  num_workers: 4

encode:
  bsize: 64
  num_workers: 4

hydra:
  run:
    dir: .
  output_subdir: null

defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
